---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:sentry
  namespace: sentry
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sentry
roleRef:
  kind: ClusterRole
  name: psp:privileged
  apiGroup: rbac.authorization.k8s.io
