---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sentry
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://sentry-kubernetes.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sentry
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sentry
      sourceRef:
        kind: HelmRepository
        name: sentry
      version: 8.x.x
  interval: 1m0s
  releaseName: sentry
  targetNamespace: sentry
  valuesFrom:
    - kind: Secret
      name: sentry-values
