---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBRpsXtY1f+YE1uga6wOHsH5oDv6Jcsh1ubrxdorVR2zLx7cx9BCL7xSUVmtqLZePK0V4zsstVuyBDI55GcruSFebeP4MiNk0sbIvhA66WTIoMzKOd4+AJboC5ZimdlzxuNWSPZmkZn0REBacO8x2WwY3w8zD+TrJhsiMBFEvj3USM80BIgFNGzVg4F+TeqLTFqQH0L69d7RH5+JS0BJigfpOsrcBuDVu+YRNGeB6mVsddCk2HLq1dXBlblqsDc3rZhr4d/AaTxQ5XeC2ws3DKgf5A0tyio8kCWXvFjFLlQTWHU205C5NCrlqgjjc82+nbqJYD6W4DhL560XkNlMWSvwkC1IOnyAop3FweROy4CShqyAeNUmHqYY3by/YcxRj/Fg0esGeHG/Z5atQlSwD9Bswpl68yNf7VeIoQim9ylD1aH3R/6hx2LFzqugGDnq1Z7gs8ckrNxsbHRO9t7ixd2qBUGtoVaSs+cXdSLDr70o3viA6C7ACgreMqyHn11+6dvfrNKGP68Lj0XBYmPGm5BBqthvZzjBFmGMvzlYPG9CTDS4c5LlNudqkgIfN8f4ABgLUi7uiEvoUX7moEUuQB86o4764Myd1tjTtaEhteqjAzJcHW5H29Px5hmdHXTnbx/eOWX0ofg2UzgWPO64QO7Hy/zlD+LmhrgwsymbcVnq02viuMsJv7kxTrfpqWQh7Aj6P71cGmYJ7I/qvz9PrlW/qFNnuOW2nLjk78v1FrdRq8QBBHP2pnr
  template:
    metadata:
      creationTimestamp:
      name: cloudflare-api-token
      namespace: cert-manager
