---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/rancher/local-path-provisioner/deploy
resources:
  - psp.yaml
patchesStrategicMerge:
  - local-path-storageclass.yaml
