---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: rails-env
  namespace: senior-accounts
spec:
  encryptedData:
    master-key: AgAAoCXtDMaKF+7Ul29F500cshY8yDNAT9KCmnzdXzgkSc2xcXFr3T74p0d77YcPO420qXohZGoWNsv/1cHSeMg0fG1PUT81qezQ8yrHc4aLnnrk7jhOQmajsqBZ/mKD+qylUi8UkpCeIKVHnWwVGrPlvqfxekTy2mbAGuUMyWcUfu/CaEEzZRgIgWVMGjOk02GCYs76MQHumYeERvt+kGTGDPd9C7zJKKHeQFXruYKzcaiKe5ksT+xx4AE7i0fbZg0iFwcI4VCrKqZhD1QavdwG2OjC/LLa63EK2E+tfR+hVS7BIMLYMwc3/9sowqayOlfaBGuV6Nfuo4y7lLcQrlaFeog/s7dxugAZdQZt48QcrsuJG6SAFEuIbELhJceXXDzoAjzbEMUg4AoW3pzHb7vcUbt4qbFtZkr36+2YjnjYucEmqXy2jD0xEA8pqtRgnFy90pVGegO0hd4RFt4pH/3dc9Agxlgunfr3bGDDM4FW+jZIhp5wgrlRXIKOSKuSfOhfeLq2wtRInS0EWdreWj0Oc1VnTQ9ndcr5qUwqSsUV1wLYDgv4u9vn4YHPEGmYrbsotQgMxIhb7KZoQN5dBN198dzcEfU+/0hl3mMK1FpM4lQyuIcqBHATzDWuLdiyaRqV85KIRWhlam5OORrg/SK8DeTlIlCrrDBi6WKPWus8uhY0N6YzpRm5qVk/aTg8vSEortlf9WP9wm+clkgad2DlP/THrwVioQbymSxs6kwpeg==
    sentry-dsn: AgCgPfqNNlHAvb2zx9cgWy40pja1J4YtjOMzBpPBYCcN8GcPL/mz84nD86JixZiirfbtPT187r/2BvkCMeXTGjMTqb2B6hdGoO+06F4cTmOJlk4xvqI0gvwL7W9MXflSv6XyhV0WPoY8TiiiFgP5K8AInBkSc729XZ5JJKdbxzsOlEnVxFbRUxTT3tgYiuLOEToSGfIPpgovsmsRUhfAJy536Mt+JySJwN98CRAvbce/RPfA8uv+6xPA6/Oi4euV2ACb2ar4jn01ESlgUt+lsYAfCMKC/dEvxF4TuedZ5YSpt8CCIUta9qVJLUHHrds8rEMn+Q/dkpIumRIyUXdLWlu0PFWCgdHKKs8454BGILfIeHVWF1F8uxudgmTFG5PJ9reEP20iknvq5/RUf/Emyby1almoFn0J0RBwfTYNNNYqSYfKzAR/320PDF8ur/R/d1AWstx0sqPvgy3/InrpQWPg7z+CVZ/thrPDHrRZc+Wb9Co4frkQR5o8ZQGvbJWxsBhHVQ6omd76Xs8Sz+cLLs1spFEbgKxaWvqXwGKDbAgYH8XhH4bkWk/qtOpC8qtOnZEr6hyEXsBlrgXVZtI8kFeiD3CYBLdZKQIjnnFsCHe4KetwnZBcOha1JfR9nQ1MBmbie8AFHr5pAnl0snhz2+9gz5ZQ3UrPMN1BS29NdVpSeAvhyiFOnufyyr0HqXW6bzBKnp10sY/L6+xyozSFnLSNax94krrOTqCEv5qyj2hJxYsg82eDRgEOXJXt6DWe5WlTdqwhBa3d3kcg7ou9iBKe
  template:
    metadata:
      creationTimestamp:
      name: rails-env
      namespace: senior-accounts
