---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: rails-env
  namespace: senior-accounts
spec:
  encryptedData:
    master-key: AgAzEzoYw0ub9PmgB+beaPUD3gkX0yEX6gcSVmQWzwj3QESpYAiP8DhKMMygqUyMlKK2l9121iJtz38PM6PJ+WuSW7Z8QDWbznmrx2OEkdgBWOy1W6U6165gvun4e1DaihU10Z1f4IKFj7NToGGp6rmcbhjcrIrA4Csb49UfqkGkjgd/iq89GUcfieNX54QXSwNqBzbCRyHVvDIdtITkHTy7v5AB54RmU6m2gHKt4QHJ+F0GItyvY3DCpQU/i3Wo0tgfhpRvhAHgFkvxbYNyeDUz67KQt35kCJQH9V48Mg2Pekaq/YiCcoYC/QmqxBMXMYfALyF17uCytVvDeWf/TlesU+qAZDXk/ksFoIsWJ+8L01iSeF5y8R6TrGEZrCSXCOwK1SEL9qVYTZOHq8vaMg3Zt2uCZk8DEuHbnX9xGOzYxI3g2vJswNDpKvLekBM9+TGrGQ7T3fWAkxbcHLnA6noBtl5EkRDOf7h0vtljn80v8V2DqPyvgg1iY0nsDE2fVRFhTyIJfMO7adFFDd8o4r1B1sJKcIC5+Gj+UMvjL3BkwnwilcUlNEWo7uRxToNj52E3l6eM7iYgkaXRHmYgWvI3COJBtWHRDm1lEt9Q0Ju/zvbuIARbpu+Bswfnj3GwvyIP9nWN/KKK9PQxzHP7ffwAr/6XRKQxcmmJ9ObXi7lxJpfLLsWPlB8cJ8W7h+zocvjHJ9NUeuIiKA6MiMeSs325fXF5kfdstzTaSULqmxPwwuc=
    sentry-dsn: AgBKORZ+MH8XAgsJSKnr6NTBlnZLj9o8q3EammG8ganhQLJXom/oMa1mj/vpUqVZZEuJJX8QMr72f+Cz45ZXGFaf8vCcpdvHP7wh0sK+G+M7q4qC5vKE5nDStZ7NOj2tfA7pf82blaaW9m3wtYqb/QOb42qHtj+IMQf4a4Jo1xbU+ycHHja4n4hyP6Af6RIpkL9lEPY61SQbmgfrZPTJN+dJo6GVTjBG8IgypdYb/B5QhprgZqumUeC5O5XXNjVu+wDyRGoGmhDgCFBhUSyiBT554V1AhwL1AA2an7aVWfsxVMAqmMNjJHzRvKFfwblN14GXilOyGR7R7bl/SGyyaZO4wqOTYzKiGla0XLd37Umh6h2aE4AtvD4P1XKb5Fnq8ZsDB4IdsqvJDgLClC8AIJHnH13XBFZdrG47By9Hd3mfnivU32muthZfyjDAh2V0obHSiwv0cVFrrs1RePlcbd5Nl0UcBWJnGtOKfpzTcT+/uswGcBtx89KCn1Vf4nBi9XxsW94naEwyBjYLSAe9+EEvnFYyNx8hblQ9YAUQ8SedPEIYB1dkbhMBRUZr7fLStp6MhrctkeuXfgMo9nfcEUpt35XDNNDYlfZn/ENlc3Gq2/rBW2MDsNlyak5XTMQ1jB8pUXEeqPa+W+33wM78mzB9Co/xdE+GAZh95T2yKo6e9Ce4fYuuk0nBbR2EIGSMR3q/7jxmvjXVUNK3J5yZJ5eBiOX6nhxrZztVFgP2TLGaBY2/g2E635PJt7ykZy/5zxMGlXs47ZfU5k9M4PSOb2jz
  template:
    metadata:
      creationTimestamp:
      name: rails-env
      namespace: senior-accounts
