---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: master
  url: https://github.com/rancher/local-path-provisioner.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner

