---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ci-tls
  namespace: concourse
spec:
  secretName: ci-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: ci.realliance.net
  dnsNames:
    - ci.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
