---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: concourse
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: flux-system
spec:
  chart:
    spec:
      chart: concourse
      sourceRef:
        kind: HelmRepository
        name: concourse
      version: 14.x.x
  interval: 1m0s
  releaseName: concourse
  targetNamespace: concourse
  values:
    concourse:
      web:
        clusterName: Realliance CI
        externalUrl: https://ci.realliance.net
        logLevel: error
        localAuth:
          enabled: false
        kubernetes:
          namespacePrefix: concourse-
          teams:
            - main
            - senior-design
        prometheus:
          enabled: true
        tsa:
          logLevel: error
        auth:
          cookieSecure: true
          mainTeam:
            localUser: ''
            oidc:
              group: realliance:concourse-admins
          oidc:
            enabled: true
            displayName: Realliance SSO
            issuer: https://sso.realliance.net
            scope: email groups
            groupsKey: groups
            userNameKey: email
      worker:
        runtime: garden
        logLevel: error
        baggageclaim:
          logLevel: error
          driver: detect
    web:
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' http://127.0.0.1:*/; font-src 'self' data: https://fonts.googleapis.com/; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; require-trusted-types-for 'script'; upgrade-insecure-requests";
        hosts:
          - ci.realliance.net
        tls:
          - secretName: ci-tls
            hosts:
              - ci.realliance.net
    worker:
      kind: Deployment
      replicas: 1
    podSecurityPolicy:
      create: true
    secrets:
      create: false
