---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-admin
rules:
  - apiGroups:
      - agones.dev
      - fleets.agones.dev
      - autoscaling.agones.dev
      - allocation.agones.dev
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-matchmaking
rules:
  - apiGroups: [allocation.agones.dev]
    resources: [gameserverallocations]
    verbs: [create, get, list, watch]
  - apiGroups: [agones.dev]
    resources: [gameservers, gameserversets]
    verbs: [get, list, watch]
