---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mumble
  annotations:
    secret.reloader.stakater.com/reload: mumble-tls
spec:
  selector:
    matchLabels:
      app: mumble
  template:
    metadata:
      labels:
        app: mumble
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      initContainers:
        - name: setup-tls
          image: docker.io/busybox:latest@sha256:0c84387d6b86cd74630b9a6fef8aeee7abf0553a16766329767083adf191286e
          volumeMounts:
            - name: tls
              mountPath: /data/cert
              readOnly: true
            - name: murmur-cert
              mountPath: /opt/murmur/cert
          command: [/bin/sh, -c, ln -s /data/cert/tls.crt /opt/murmur/cert/fullchain.pem; ln -s /data/cert/tls.key /opt/murmur/cert/privkey.pem]
      containers:
        - name: mumble
          image: docker.io/goofball222/murmur:1.3.3@sha256:1480d63d4da4db7d8a8f5a96b6abb9d18a17166e8552f03aaf03d7c38889c9e1
          ports:
            - containerPort: 64738
          env:
            - name: RUN_CHOWN
              value: 'false'
          volumeMounts:
            - name: tls
              mountPath: /data/cert
              readOnly: true
            - name: murmur-cert
              mountPath: /opt/murmur/cert
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: mumble-tls
        - name: murmur-cert
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mumble-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: mumble
    external-dns.alpha.kubernetes.io/hostname: mumble.realliance.net
spec:
  type: LoadBalancer
  loadBalancerIP: 104.168.45.231
  selector:
    app: mumble
  ports:
    - protocol: TCP
      port: 64738
      targetPort: 64738
---
apiVersion: v1
kind: Service
metadata:
  name: mumble-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: mumble
spec:
  type: LoadBalancer
  loadBalancerIP: 104.168.45.231
  selector:
    app: mumble
  ports:
    - protocol: UDP
      port: 64738
      targetPort: 64738
