---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mumble-tls
  labels:
    use-dns-solver: 'true'
spec:
  secretName: mumble-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: mumble.realliance.net
  dnsNames:
    - mumble.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
