---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ace-tls
  namespace: realliance
spec:
  secretName: ace-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: uf-ace.net
  dnsNames:
    - uf-ace.com
    - www.uf-ace.com
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
