---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "onboardingConfig": { "extends": ["config:base", ":prHourlyLimitNone", ":prConcurrentLimitNone", ":pinVersions", "docker:pinDigests", ":rebaseStalePrs"] },
      "onboardingConfigFileName" : ".renovaterc.json",
      "persistRepoData": true,
      "platform": "github",
      "autodiscover": true,
      "gitAuthor": "Realliance CI <ci@realliance.net>"
    }
