---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "onboardingConfig": { "extends": ["config:base", ":prHourlyLimitNone", ":prConcurrentLimitNone", ":pinVersions", "docker:pinDigests", ":rebaseStalePrs", "group:allNonMajor"] },
      "onboardingConfigFileName" : ".renovaterc.json",
      "platform": "github",
      "autodiscover": true,
      "gitAuthor": "Realliance Renovate <renovate@realliance.net>"
    }
