---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:24.78.0@sha256:186226ba9e61e54c39b6a858f8acad96c04b93eaa149632324bbd69e2eeb3d23
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
