---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:24.97.0@sha256:de90e909a5d84c9f9aebd67265320e7504511e2efdb56ca21266b11bfd279858
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
