---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: renovate
              image: renovate/renovate:24.28.4@sha256:c91fc29a7b1b1ef7367905f53d2449936bb58e20cdf41fe64d4d90c7ce3869a8
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
