---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:24.119.20@sha256:c08260397d2cb5b4afdc445ad642f602d14c84fd8e18fa2660648936bfd5da70
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
