---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:24.119.14@sha256:57c8d667fb85c2d18bca0749167d3b88e77e3c81a5ecc094a0930a9bfb3091b5
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: renovate-config
