---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: renovate-env
  namespace: renovatebot
spec:
  encryptedData:
    RENOVATE_CONFIG_FILE: AgCa8HL+lDMdxCw5SzY+SqbUcOdog19k0v1XfUydwOUybi/Hhz/ek2HqG3gsil9mewBJv3ZAqIwEQuHvACscMcoAgOCovN4rHi94FMITS2nnBQqDKqTopQlnQvwgwGlBgbQ1+OnMGLgX3SkeNoXEq/uQ4dbxG4a5pxSFQR/P6fKwPo3/kkIAdpVZc6AzzD43z2JspfUTEHNBjZqHflZ/aUxCZPmKPiX7ja4oiTGP2zDf41UqYTgCxV27Bx0ccvTX8ATxHvWNstnvcDVbfMz0hq7cy43tPGHMKydek570DSWpapt5xOZzvNp1ZGXGVUixi6jpTqr06MeBPI96rYhfjd69YjMKZE2eDm1LuodrznsJ/eGjnYgYmswhY6YG1N6MwYxn3cj99rTZV0c9jKxEdz6RsH735opgkRhgZeLicWMSm2DKQQ4j6s/T8NYkduSzkw+enu+6bbA3XjgYnVxph4r5VdS8EuI8VKt0BJRPzuVGhNF8PHdNQVb2roJIq6OxISf6vBPawsr1yNj7YAsK/TJS1JCp5hMXVYEJ8RckXGQ9FguXx6KBQ96O1h/2SwexK5J2pWbHryjUlE1GgMjy7PBkwU7ZWqjREh60JYD2RrcaskeVjbm/7APu/PhE/GtnewI0W90r+CsORnvnt+77DK9FO/5+rc/Uq+m98h6gRhMx1E13a8fdv6uLY43umjLgKp3B5SN6pyozCjGwysGZCz1n1sqG+CrQLH7H
    RENOVATE_TOKEN: AgB9EsvnjbZX3t2jpq/ESEk+S1fHBVGxbOddK5f0UKWv0qi7B+ErGAqsVpKjKrH/dw6rSZwzpohfcPrGPEnnRiTwt6e69oD383gcBSlNiHiQApOQ2KD4ZU9ofGNdFavsV+3Pvn9EQiyDKT+AGGRzqsyRnSBFTccv5hw3LvNPnU+cwHpmzSgTZecSJBO2jZFzSC6lDnRqw5FRHNoJ/sgDBqtdiru+vC52r3rTvTjrnNhRaMAKR6z4gvvysuSkgCqUd6ZA+JvVN5YyPUCxBdKlZeZgikLdZKxM0WvOdWJVEhJewS8+uxR9YQ7fc19FOB5AtR/wKTOeH26VUxFDfuo1+QP03nQeLwS/AHjtu7cU8itnkyYZa7mnNt37zS8zb8kNflngWa37fEgxsYFUsmLJ3ks+3ucF1mPx8x4x22uZPzNPPk0JdHkSEZviwxxpTpeJT6ffNUmklzGF2sZmHlCAIJmmnkU3Nke3c1X8Qy3fHd/lnArK02D4FQmHOg9/5mFjgP/tm6+4TW5u2/+4RBPWxvHmtS5jKpR+dwjKGN4xgqxQUALurQWzrCweoREC+9sN5YggVOcLgSdqFotPt0c0VdRQqw/3Bn819KhMGZOWjVOBJJa4DBKTp972m2shgvVY/X5miBjpMZ7o1U8uQjXClYMnQvEjQhD+XkUQeioduh8NMPDIP0tEnqjv5eN+XfqFcGhTQKXPbp6RpoUQELL9lmGURylmM4P0B0Xt4DKP/6uMv6nt3u1/r1a9
  template:
    metadata:
      creationTimestamp:
      name: renovate-env
      namespace: renovatebot
    type: Opaque
