---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: slack-cd-all
  namespace: flux-system
spec:
  encryptedData:
    address: AgAq94+UovICdjljyBCbwR38E0Jbt/hITCGmpT2YKCrurVhm0bYXJxhuk0J3rTnpv1P6b57avKa8QWnXwwkY1CDfs8wNCu2GAwd+UpQUKqLiwEoZ0pRQZXmsVUJG1nB9sw3ZDnAinbsgI5o4KSRWZL3K1NZlEvXQ0ekGxPoBPDteDF9qQzq6zAnK2bUsBfd4jM33w78lD7Rpfxj3ONnEaIxlOEM0ukjQnVFJ1eF/rFquGgpMcHul6I9EfZTQsgZepzN4QEspw4kHMSYgVjPdGy32ZXirSUQRk5U33OXtdKN7tHFYqSPqirYAOz2N4Na5hU4KgFpF9vi1ERCZqwt8ZIFXSNk3h+9p8JMkian0wuvCTWb/GYKUKakIQY7LihchblBHUQS7kWD36agm0Y0ng79du5pY20X0OrzX7Kb6jlu4o24PDheXkAyHMN9jUMKX+opjc+PRrvmNUrmyYykyiohT7tx7uudKl/87+8eb3g4xpmPelCT4RGuAOYuZADSRW3yzh2JwxF1bkQpjPz48IOpbCG4XyUn2aTAEfIJBUqauQ9ct6f/IvehQcwDFcQw8zLeaDpB06FJS9NMrxnc/qyIOxF80Py/UzC2MzL3XwKnOztmV2hkTk746mnJHfMHK4TVKB4aYhhcvHbn3+Gt/gZKX0AZ9vhtc/K/xdxr96lVDWh1C4/P9ttchIiJn4IbI/owmACZD995Xbd9QwDSmeTFrR0keHXuBIJaqdkF/c28GQTZkq3RCP/P6i12l6cX185RTbZXAMxPVwAz9U3xSgD3BnYGPka+iYtm1q0TgBuAO
  template:
    metadata:
      creationTimestamp:
      name: slack-cd-all
      namespace: flux-system
