---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAk8u2kjZkKIzLuQEBh/lzvxr3+7KBADfU2mbm0IVSpQvYtoULq4NpZLI5bRLCPA8ruTzXZuzPtcFwsUS30jZ0AUU+OUK57beZQndyhvmhXg/HtplLD9++7HsFXaItPd7AboZE2AtMqbn63Rp6zQSv6/DvtCxgEZ6+Nk35vVdkAj7Uc5QB7m+rRPBC1P+IKzIcY/qIG+2gd3l7TELUfccft8My0QHRkK0vNJp74xGe+hdlEtu8t//n/N6MwziTJv2FdmqJtZgzFGLIaPT6JpV10YtedglluqNOajyDT3PE2D6k1yZdNL/7Kox8F3v7612oAOWDYxNU8cLM35gJoj7+c2jTUE2eJvEZYbof+hdeqJMWFf78Jhkz7hOfNNOjbw+He6Sa2+SKvpAJyTSPJy+ppao76lnTiWwop7W/q9hFggNyOlMxVf09n8EKMiG7Hh1rW0uWfkpsXKAr4lL7PahnBIi80AgkDHjvWtDEnO/kgF/anlyNh1ON8VRHNa0KN6RVp2sUhW7e+XkNaAjm2o3e9oFjUaYkjrQkOe2SF8BDNNl8nK+rUpZPSHFTB1fxjYeyV0KH+rrA8Olc2d78KwWKk4htohGZ6NDCbbzi3xIdhM/SVOH67cf+r4Mny14o9gtGB5vLPB6AGBFOiRcMIQ6FH2C3lDe7h5llZIjqOVbA0+3ulWToOfQCDhOm2u31+yAe8eE5AYEoVUA6nWibnHxVxuvWb63TMKHMSazvA3U7CaB6UC8m7Ylvr
  template:
    metadata:
      creationTimestamp:
      name: cloudflare-api-token
      namespace: external-dns
