apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgCP/RAZIK/BKJPW2IqfAapji7E1FjCByD1TvW52ZajSjcBL+KSTFveNibn1YTMiAOMB+y9LBf1l4GREd9OBoI+C0zsnMzoKywqPA1Bvq/q1/1oj2Te2Wlyli4UBPxCY0jNBS5Lt/sgn+0Y2eqoyv8PXaJFQyZV5UobeMIS8KBT+4peGlgDIt4fKXV0ZnZDgaFCUj7l4t5+cx8csq9+eJFH6J2QkM2lg5LtIBoUIqUx9L3bWMwT93EXWQn3VkWtMuReeSGYiW0+11dW8GUf2spQhBunssHw2g1DFDdXlomm+ktKnqduV/DJYBOIDeuoNYisjdEPeSaJUSgjCrif1DUYFtOxL2aCwfddnUIOt3wqdvYB/UgmWQWhkrj6lqJ2H/poBv2Gx2ZaitgSFabk0da1g99DQP0GZzntx43fJlJCpq7voIYkQNXPmUhJfRjrUXDt7VSlk6WfrzZSmk0c5GW/MJLFSjEDREAYQS9n29HATktHQJhi/GCSHo5Rnc6BdsQQ7p2koM/z9g+hBK2OWv2AFwutY5AmeO2PALeOGaySn0BD+MqdCATWtIq6OxUzF2lB0ATlGqozSH7eSM9IVgomButNHFFEWHYXkv3fT8wTTUmbki1qlf5V6iFxcLUzBV0ioI1dElRjmB9CkGAxMbvhubJS2DbtzqTw9Hgywn1S9Ii0mWt3/0wrRBxpw/Fh65kulqD8YimyJpDUFYy8Sl/BnrX8pe383eaqG9m/sn/OMUXu2ME9lOKDeXtwm7JlOMX3tO1qG3hzIt/ojSftDSmn7nnMcPEglfQ5JUhsOQiBBfXiXNYfDO3XscNomcEfiNVgXFAYqDsoVSZHK5oYb9Dk+md30CX2bX2ID4Nukk36E9SlTU7iu4gZfb5FbU6G8I/Ek/kdvsMu27x+wsBBIoUustCGuAu9u1eJxeP2X9So=
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system

