---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  url: https://github.com/metallb/metallb.git

