apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBuSflkuJMkjCq9qDrqap5Gi01gOA/GHRDx2hyUewMiNtWtV5Oiqtj5bPA+3kzROGzzyDbtQqQxpyWXQjZCdJm90CyRq4R9HqTYCJPG49Uft+mWikjEoJb/Up9i7cAU2SPMDBQVsMH/hxTt7yj4dINvW/iVvCFOVm+8moQiiub4UxpcxCZ2XriHmtLyoSrx60OqT/ak7GGaU0Kxm2IwtR2QDryMLkMliMcE84SGDAJZxQH8jKw0u6O6TBci0nYj7KbA+tHTvDVOcu5ekkWA4cBc1rlpcT0zRiwlvoseJlX3N3r0krxvS+VExeD/Kv5fuJHjeLG5hziLAMmW6eZaRpwC8HGbSPoZOsichUi8QXsY5iDp+kD/VHroZIzsbWkIzzGxwx8gmrd6k43Bkee5tPzyA5S9u+x387QzG8LifvjV7xcRH7IHGKgQ7PrcaEKy44F4STjzPuLvccmcA6sF6ssgiFu2xYJyjUpS6ofYrTa7DSicVsT5VxZzCNUpflNW36sOew5f1XKudtPkmii/50kPfpkLqi1nVLtoMtPXUM3Qda5//l5pr8erbaV3kYVnf1/AMiO9uMCMRAnNi8FAuQWPLMaMjL7odQdxZFCZIJUU/OAXgLx5PELaqCdkzv7/E/HBiQr+rLrqpaRyL5l5INe9Nl+Eut/SuiaS02HNobPSeHtinGvcB4SZ/fqe4ZFA+AWLx7EIUySG9wlTngYns1gVCNOIyekVBlbFtujvaL4OPKUq+RBXHBahYE9yEVVRPSvbAvyiUMMB1zJr3O/ax3QOoKjay/ZaBiwE7QqJauyE3FT+Viha/4PdJIYhd4rhZAyCcM0j6cHiVKy5lmTIX8CRzK4zzm14uU+M19WNO8mC0mWhbIrFVPCwkeJYZizIxpHYtb2qL1skNmHlW3KO9+A2fk9y8w+SJT8VL8uf5PQ=
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system

