---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cozezone
resources:
  - configmap.yaml
  - cozezone-secrets.yaml
  - elasticsearch.yaml
  - ingress.yaml
  - minio.yaml
  - minio-secrets.yaml
  - minio-creds-secret-console.yaml
  - namespace.yaml
  - psql.yaml
  - redis.yaml
