---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cozezone-redis
  namespace: cozezone
spec:
  chart:
    spec:
      chart: bitnami/redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 12.6.4
  interval: 1m0s
  releaseName: cozezone-redis
  targetNamespace: cozezone
  values:
    master:
      persistence:
        size: 2Gi
    slave:
      persistence:
        size: 2Gi
    cluster:
      slaveCount: 0
