---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 3.x.x
  interval: 1m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    podSecurityPolicy:
      enabled: true
    controller:
      config:
        enable-brotli: 'true'
        hsts: 'true'
        hsts-max-age: '63072000'
        hsts-preload: 'true'
        server-snippet: |
          ssl_prefer_server_ciphers off;
        server-tokens: 'false'
        ssl-early-data: 'false'
        use-geoip: 'false'
        use-geoip2: 'false'
        enable-ocsp: 'true'
      addHeaders:
        Content-Security-Policy: default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self' data:;
          base-uri 'none'; form-action 'self'; frame-ancestors 'none'; require-trusted-types-for 'script'; upgrade-insecure-requests
        Expect-CT: max-age=63072000, enforce
        Feature-Policy: accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none';
          fullscreen 'none'; execution-while-not-rendered 'none'; execution-while-out-of-viewport 'none'; gyroscope 'none'; magnetometer 'none'; microphone
          'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; usb 'none'; wake-lock 'none'; encrypted-media 'none'; geolocation 'none'; speaker
          'none'
        Permissions-Policy: accelerometer=(), ambient-light-sensor=(), autoplay=(), camera=(), display-capture=(), document-domain=(), fullscreen=(), execution-while-not-rendered=(),
          execution-while-out-of-viewport=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), usb=(), wake-lock=(),
          encrypted-media=(), geolocation=(), speaker=()
        Referrer-Policy: no-referrer
        X-Content-Type-Options: nosniff
        X-Frame-Options: deny
