---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-event
  namespace: ace-official
spec:
  selector:
    matchLabels:
      app: ace-event
  template:
    metadata:
      labels:
        app: ace-event
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ace-event
          image: quay.io/scoobydoo181/ace-event-server:latest@sha256:0df332ff88ec49d8c22cbffc8c5cc211b3f8b70573000fc20e75da21ad72ad75
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: ace-event
---
apiVersion: v1
kind: Service
metadata:
  name: ace-event
  namespace: ace-official
spec:
  selector:
    app: ace-event
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
