---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-event
  namespace: ace-official
spec:
  selector:
    matchLabels:
      app: ace-event
  template:
    metadata:
      labels:
        app: ace-event
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ace-event
          image: quay.io/scoobydoo181/ace-event-server:latest@sha256:43809e50a9891ea6a6284308d3010c49b1bb673f05cb05c1f46a025782a0321d
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: ace-event
---
apiVersion: v1
kind: Service
metadata:
  name: ace-event
  namespace: ace-official
spec:
  selector:
    app: ace-event
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
