---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-home
  namespace: ace-official
  labels:
    app: ace-home
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ace-home
  template:
    metadata:
      namespace: ace-official
      labels:
        app: ace-home
        service: web
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: home
          image: ghcr.io/uf-ace/ace_website:v0.1.0@sha256:f278dbe250d47942b7fe69252661c3b620ebc3d762bd6e7906f9d91434da3570
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: REACT_APP_ACE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ace-home
                  key: email
            - name: REACT_APP_ACE_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ace-home
                  key: emailPassword
            - name: REACT_APP_HOME_VIDEO_EMBED_ID
              valueFrom:
                secretKeyRef:
                  name: ace-home
                  key: videoEmbedId
            - name: REACT_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ace-home
                  key: appPassword
            - name: REACT_APP_URI
              valueFrom:
                secretKeyRef:
                  name: ace-home
                  key: mongoURI
            - name: REACT_APP_YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ace-home
                  key: youtubeAPIKey
---
apiVersion: v1
kind: Service
metadata:
  name: ace-home
  namespace: ace-official
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ace-home
