---
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: client-files-minio
  namespace: senior-game
spec:
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-12-23T02-24-12Z@sha256:cf5901ea9220a387ad1936069e7c90af1f6c6e671c655f2f5eb408b71d10a063
  imagePullPolicy: IfNotPresent
  mountPath: /export
  requestAutoCert: false
  podManagementPolicy: Parallel
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  env:
    - name: MINIO_USERNAME
      value: 'minio'
    - name: MINIO_GROUPNAME
      value: 'minio'
    - name: MINIO_UID
      value: '1000'
    - name: MINIO_GID
      value: '1000'
  zones:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
          namespace: senior-game
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
