apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: senior-game
spec:
  encryptedData:
    accesskey: AgBnvD+0nYGrKZoOO30ixtsBnFgiObYWXehizBv9yTkROZr3DGpDoJSl5pTNF9JFDoYuRtYp8N5MSNiXbMMGz2okErWpPsqxLh7y3bxaUToSo8RI4FqosJFCrn+tcD/M4vR7S56fjWHwgV9nkWmuUO11niJaW8v4ZQwHQghUkMqSldw7dIqXeza6wsVRuMqrLrQgNScMLL06BinxBInMght7Yop2b8kOQxM8ASROimJAkWoOJm9U+viu939BwIS0lXUJq6rI5lDZWRbmyLiLFDdq+NEJXsi0pz+dN4t6hI0Eu6TO5HRJtbVUgKCYBQpPzwQJBxQcZ2OwtOvMZAP4LkD76S2CsDir7J/PbuWvTYiyuS6s9fJsFFhBBI8gjsyYRqyzW25TJv84SUErkOhKl2Yq7CQgdYz4n4kLa2QH5ViXPvM4RpsW8R06JE6SvzALJY6DTPVSO+N7SbcTPS5OL/lii2bDs3r2EFLy07ONBrAjpVIOAYuV0WmbEgFOBUdqDFMGAhGmZ+nTh9Ls8befslTU1CrmJrKNGZ61UqISMOqxSWCM4CT0cDir2DC6Zu0giuODIGV+35ZRlRNLbd10gU19WzATiFbEZ17IZLoKUBZrmYkSac5U1JRQpeZrUclkMm09iBJyWbBOnHRRBDaJomyRoH6UdhKm6sPJ7nrQSMwQXvYknbU6/bnVzGMELdEWB5cFiPcA53dzwESDU4pgKwN9kKJLjZDxmmb24jhvqkhBHw==
    secretkey: AgAv+DrrCCejOjtXuOP9WnRJqDlJ9pdWv2eucTq0T4SciMCJ0zLxbrTDPvr48LdHPNAmaOBmaP1sB3KgdRW0wHMiS3Vt2rg5i/vxZVNb0+of58Eay8BCYktFgWhnn0zjcHsCZGYpppczwQTztTdYbr59SIOSOnR0zae/lZ2d/DjxGS95QVNe5jTy0VFLgxMLAb8gvUfMws7LLlAAama+PAuoAYJjruR+idFLkQGTq94oZHyGLC7R1qkdDJfFeAy4w/DRev11w3ViLPmuCppfNaNyLfMezfvso8MA2ZYOlThygISa4sxQ9LhM3qgavo5FzxcyWIyuGkEWgleulnRSzJ1/1xJ0AFXop82Lw24nfmQITZzmVP7WFr1YBuU/WfWeWjBSXqNDkWBielE5VgQheZqzAGR+i3kzFksk9E2xucH0k5YzzUc8B9d36xXQ3vhsHdJ6XcYHbVtw4nF+jLy6Z3hdblyl7gYwI1HcL96AafVJw+AnSc8tKqILS/df6F+Y/iat/nKAlI5QRvpjqZKq5njKaIF61gPPH11VayYheBTylyPeBUnJ5K+xeU61NEnjF/c/7aXiVhqHvc4k2X2e37T7bXO5qTW+loa1c7dlbmYGX9kXQTUXn411ZIZMFj/RiyyjHV96cG3jUmqQwDFQiWqfD3x/QGG1aHD7xdITtj15FsyVeJAYj1Jv0SXlBHgpDOgbX/9bcmvBUvohZbY4dtLlbRYSmMaYkiSZ8TExiu6qGw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds-secret
      namespace: senior-game
    type: Opaque

