---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: client-files-minio
  namespace: senior-game
spec:
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-12-23T02-24-12Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  requestAutoCert: false
  podManagementPolicy: Parallel
  console:
    image: minio/console:v0.5.2
    replicas: 1
    consoleSecret:
      name: minio-console-secret
  pools:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
          namespace: senior-game
        spec:
          accessMode:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
