---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-pods
  namespace: senior-game
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: minio-pods-policy
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-pods-role
  namespace: senior-game
rules:
- apiGroups:
  - "policy"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
  resourceNames:
  - "minio-pods-policy"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minio-pods-binding
  namespace: senior-game
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-pods-role
subjects:
- kind: ServiceAccount
  name: minio-pods
  namespace: senior-game
