---
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: client-files-minio
  namespace: senior-game
spec:
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-12-23T02-24-12Z@sha256:cf5901ea9220a387ad1936069e7c90af1f6c6e671c655f2f5eb408b71d10a063
  imagePullPolicy: IfNotPresent
  mountPath: /export
  requestAutoCert: false
  podManagementPolicy: Parallel
  console:
    image: minio/console:v0.5.2@sha256:436cd993f0cc8639e8d7d902eb0549c59e701e93887821c9eee4c7586be879c8
    replicas: 1
    consoleSecret:
      name: minio-console-secret
  zones:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
          namespace: senior-game
        spec:
          accessMode:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
