apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-config
  namespace: dex
spec:
  encryptedData:
    config.yaml: AgAi9pBNQuiub/RsJHUIdevrNZ2hXFi6Jy9qPFuQJTSRLRB/k0w1RGKntRqEHA9YZmgi+clkU2LijZakadzyW/5wO4eqmhxYGKFk7hR4o+G5uMGQN4cWgJqHB+X9bQO4Q2c4JVh9x/rUCXN3YDiabeS6mdKwlqQhsp/LWyF6ouzDj4FF7qePF/G1Uoit1Z20CmE8+9lm+p1M2Li1uF+aZ71h0ZigZfmlolhlJ1Pz20ejym1XN7n6qHu9lLetdkDqGwWv4GDBLs5aP4ncBz61s0K5LtOsi/c/wt/0sVr3pnghZzfG1jhRQQzV/tA5xif1ko0en4VUys5rsUUbpKUhYhbSUXTMBxupTKqu+uJtl2My1iytZRlG+yj3d7n0W6Rkfr0JTGde9ytGpE2QXNYwG6Umo1D/bBzG9l1N2EKb/9S2RW6eV17BU+HLrtT/nw3ixns+Lj8n/yldDemgMTRfa85qiLRMirU+RQPT4mTj1EdNQvOqlSROrvLI8fuAFn5HSKxhH2h99X43FT3jyoeUT6Nt6cekn1WpK2RkaE6m92hs+Ov3rhiufO6J7sEORbrwApUJp2xXe97XS+DfDNRNPfZ+/12z3T/yfXPda4CqdBq+KvvCQOKuDLsIHStwrGwhsG8acW4fz1FYSX1qY/yRy951YL9jtVtI6Ne6c40dBUG0gOOW0W+9faz2n3pavjMBQBNfX13s0FTzegTokGGxggkN9sY+0oae2W56bgvNYpmfImz5UGSI2UIw6hIhbSlrokFsmA3Nzo+ZN0KJT/US1GJldw/8tNBnH0H+ZldOlfhCRmcZgW6aoLxDWFduFqFWi0zqMsMEHwNFHALs/m2PGBYdYH28zq0mNemC3mxgJQ1gf4DfKL5zOg/w+ky1Uctyvj7fF+aChDFxRTwB+YQlAumUrvzujTlTgBxq597gTtsZeFVQh0UyuRYvyfafr3sCHUScy3oS3rWuGdedfbodLIAix73mSdlm/L6isdjHgLu13oyrx+VFJ9YI5qg+GJs9ueu2arI3Ln+fhevuJFcgxxUc56UOEHz4xmD8D6iQFvzW8oM4R/QM7VXew8DJbyegnOiGo5Lr1VuMNbWWL1L4w+iN9oQwC+xU15R6XHXu+z8sUs6BbCm0Bc3OSS46v3Rou5PtdJTGGjtWCWYeMQ/6gWw0mlRKBRNlgJvRYr5eU9LoRi/48nL0VSYTjNtSPYXW1Px3beMP/C6eg/nkWXbPLbRlcpkDHdiHNeGZ/Qjn07F0V/hOFZPVZeaKy3yrsBa+iKO+cRmdSrmJsKJG8BWD8W/8sHEMiQAWvJc6m8rJypRKIYieM2zNhG9kTekbpuTfxjVbY7DJjYmReDciU57+hLb1zz26T/jnwc/bDIFnd+SfcaXbSlLB3IiagZ5MZEDJmut6PNt4lXHlrgK6mZdEfqMwxwe7gQ9UqXe/8b4oUNFV+OXcz4El6LgYjK3AQxl+EumjV9PBFHfbM2+2Z23AF186xwJsRiRKXot9G+34jYsYH4xUQd6Ykc9h7CFaTBZcHOmdv/tJXshDzY7GQnj6ACNv2l1i4eZGk1DHh/kjLJjvLGWA/o5B5gusvHfzELyBtkWJ3O2AS/YfwXmLUM2LWUCb2U5Ad8cnMIf7egKRdfEcC8lfm1zMmMtBL13wdXd2tAVBp+FLnsrhFusycuqYDMLAkwE8jkWgU2rmYK1CgvXYgHgYoE5jTMiLq2khmP6OJ5IWJP1T8xyaYGDzNrQ=
  template:
    metadata:
      creationTimestamp: null
      name: dex-config
      namespace: dex
    type: Opaque

