apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-env
  namespace: dex
spec:
  encryptedData:
    github-client-id: AgAz2el9J2nZeF40XuQ1NtmLQHwO7DFsCLeZUpn6fateK6cfnClQIe6PO/kFEc2F37JcUvpH4u+hE/3Uo66taUkXSj1+d+3kFufpXbt96yZArScbcYK9JV0HTlab1KEBxL2Z3Ju6WkiZ03PJZrVrsQns1VIM7Id3PgcHTNUrygDqQZ1jtlPdBatdG0nFb7gfknmNnw5Pujpq4ECO1Id7Wh1D5JXlPdgHnuOSG9wGjBorT7uEvIakyYl54YQqw2075mwPGG47HXBplAI+M+4QY3Zj0m3wgrX6u9+jVc2qejLNbc99o+kYzCP+gvX7q5Uzxx4MLYOuOTZeXj01x8ZRenhSZbrHiCoDszIztgcB9oC5PvX/zvXmzC19qRQz7jIWNjnD2jmd51i20kYaE8hUqviRfG7xi4TTDWKj2PjDmOlliaI3BBOM3nheCHP0AONaUSyYqy+PvgbaF4K48BIzkIu1CFkVATraifstuEfJVWTzrr2lmq5w/ScuqCUOiOrB1mPmNIsZLPjRqEpxcaiUmvpUsrgdJtGi04Viqxc1HBd++E0S6zbJ7CD+U3mDTE8YN7qGOhoR67K7LoEgcb2uljO/aBrPCxdRHcTakbPlixfVxBaBWRPtnj92YmoLOOJNtJpHP1yHqQNdinpQLaxpdg8tJ1UMSLz9YtHZWdQOJHvga3gRTAeZBs3jWuCVzN+buAjVH2eeKsuvz2TwdJl8H4umBHT5FA==
    github-client-secret: AgCFnZgLkrbInibr3nd9UPUzbOos7lOITfwGBOD34CEk0Z4R+Xg/1TSr5oS5yXd2HY2H+vrdi4CzKW0gz5xwGF4VhSormv3z5AYeYZsa/dqDCS1XBjHpHrOdAh4cuuFASC0JXT2cTwsvcET7+lf9KgyFjPEAclugmCVz8PbexO9m/YEYzqp27SJ3icXJWDqvI0AnyVFA/pE20OLaKF8CfHh/Mz3f234ZHFdCgoPocFeR9JfQk+noB15W19nIPMZZm0ZPIW9kO0iXtXwk5vwyxH86KPzt9YysITzUmI6OH1xbEvC6F7sbOnNW6EqMcYW/XeRGXrR7XmcwoMvMvIxGTMX/3FcQzVkQOknAjkgAcAPIPeh79OF7g00etzweY+W5mv2ByKf/M11cRQ2jYAiSCRl3XKl1Jm188QW9iRNPl/Rg8HjMlr3MP08bsCTRBC4OQZuZQbbKw6vHCxzvVgyr7tJZh1VsOwJh36sNc2lB5K5pOjX2hXeZdaCLt7vYnIXe3+gxoPH/Kr3EvIcG1LE5FUa9D2Dl/lP8y1XSXpdB0nsZEtOFhv9zDPuLn38IQeWlS9YVjTpD8hnpMo3oVC9vT5ocKIHP/+yV114S7SWW4sekTNdpIxMEfFt0egcw4I7SuM4D2/X/CHLXslPsdJROusnv6RIwTxilcWHct5QDcXyEChz4F/NJG4XFexHXd+ofsvPWPwrCIEV6eLeHPOhMySpK1xBuAz4S4gqJIb1Dc1Jj587ef/e97wHK
  template:
    metadata:
      creationTimestamp: null
      name: dex-env
      namespace: dex

