apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-config
  namespace: dex
spec:
  encryptedData:
    config.yaml: AgA8pYjB77DW6xdlAg3MfQWfdh2REz41zMKhB/WXRiBIcGFYA0hlLhZz3GzJVuVgUGEpWoXILS3hKBdy5iyhc8ETVJrTWJUBKT+zeDsP+yYpGgWGhQEpS2cZJDUUZ5SksyjaAdGZbx1eXxriPQx8EKr3sx7UOwY1EHF6skqm5GMKEOleninbni63jQPCJTmSa3STRxyfMLC0fRKqQGH9sb46Z1EVJJ95CB+cy+oNCAfzH/hwiGicvQCszKH/BbYGGOvvkSoCyLSAENLpAZL7KwHafupt/FH4gkYmapUtyvELk1eStsG0IW6DKpWSfGWGWuhzGk9EFhDVaRxsbnMjKfprzU+mk3q22IIA8pUbRu9WWSJy9G/ZLOw5rKuMZoeru7LZcuGaw5VAFm2SJIAPu6AyDvQJY0YcHJcU5i2lRiOZd9cM6WtR715qD3vaeL2mFLqA9efCK/kGHnjXiTIgnMzgPSOrl6nnDkeFcJXKqMwE2DbapLJaJgAF5BIBoiycWZ3MFvRJ5nIByxlP1UVER2dgoR/NjfumrwmK6zU+YJAW+fTAT7EFTPIBm85d+SA9w8HiPxp3cffzdEa9fi8QsYPMUoXglUbIMTjkSiaD76pT2QMYxqaw2QgvSvJhMnjhrlHqzCTQ8biepBgCy6Tm55EbPEFNeXJYmsGMzk/0AOxC5f/tBB/utaxd2X/TMKe3GomMB91+JmtDfufVwU3zcVV2F/wuaRbp+yP8GJonJeNv1ZFcMmncIC004er3Pg55IMerl60D8SrewYMgbKTi8pIxNDYy0JfkEUiNj9rwvHMyu9Aq5pL/pHTH+dUKhhrHplGTPyOxOAUek7DQkRILvS4cb8DimwIzo39pO5x6SHQUL6Ned+rh7d2jV+Ue6PDs9K11VnGbod9UAk6izhikDaUrmNQt+RZInbBNYdx7FTuCVJToUu98JnfZQGigBgojXCFCVbzEqUJGh0RpIA7QCnlCZcn/4SGzrVozfV/hCMzHany8rD/+PwgzE4+nq6u+gUygSAChRAFfHuQ3e0zjyGzQoaAEpWuuPUaqQyvasKYLNHsI7xDvhG3SFWOME7AOZe/1bvx69TlLYXfxv78IZ3fZzw1+FlbUqqsaD4kvcG+Qe/oi7++FETEzpaHuIiBKIMtkVPfRyC7XqW6tmXVAB3go2k8AUAOC7XimeVXILkJcciTJJRIGpjbzCekYDf14Q5MtjJ4z8EY+/k/UQPsWepbPrhancJGkTbfBjUx48BhGoF7YzUmLHXRAG6fcwH+Irrkr0tzqiw5Xa+R+UhS9eoHI+34r2uJ+9n9gR111FU6LkwkPvXwnXF3Tmzv5L4kKXumLE7IUKvgt/uS7MSPPWibi2CXiFfkjbfWXHZlvK61BA7Ws7C9EnWKHIcq3FgyF9lvzqr9pwa1pdJ1KxZ2Nc1J40SdAjW1cASiYSAg6HKtPn5rX9cnrDrkv5Oq9eDi+lXy9yBBWBFRMM/PyXLkN91EuNVSr6XxprZfAsW0a5ANNHLR4+fuk5MzzQhCw/xtJLzdWUzPh6XZm0khmxCoA6ZPI4xYXM3XkDRNhtUcnIL8yoLxYF/H3csPZPt4wJeFSElWe31X6vJOYUmA3d+1XU1meDmvViQiSUZ1FbIo+sg+dwWCTdL4abIIaR43X6fW9mAMTED23hdbRnDqluNhLfoydsSiUR9ZIs6KBi0Sz7x6d41WmjI6ulT4xSwtWpJszrt4mYDbj4WAqneEKiSvyxA==
  template:
    metadata:
      creationTimestamp: null
      name: dex-config
      namespace: dex
    type: Opaque

