---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hci
  labels:
    app: backend
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      namespace: hci
      labels:
        app: backend
        service: web
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
      containers:
        - name: backend
          image: ghcr.io/gatorcomputerinteraction/db-backend:v0.2.1@sha256:524cd415aef4aa61c8573de6548993bb3f874d10e556796fc707ef754a5ea071
          envFrom:
            - secretRef:
                name: backend-conn
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          ports:
            - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 101
            runAsGroup: 101
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hci
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: backend
