---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: hci-db
  namespace: hci
spec:
  databases:
    hci: postgres
  numberOfInstances: 1
  postgresql:
    version: '13'
  teamId: hci
  users:
    hci_user: []
    postgres:
      - superuser
      - createdb
  volume:
    size: 4Gi
