---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-database
  namespace: hci
spec:
  databases:
    hci: postgres
    hci_dev: postgres_dev
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  postgresql:
    version: '13'
  teamId: acid
  enableMasterLoadBalancer: true
  serviceAnnotations:
    external-dns.alpha.kubernetes.io/hostname: db.hci.realliance.net
  users:
    postgres: []
    postgres_dev: []
  volume:
    size: 4Gi
