---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-database
  namespace: hci
spec:
  databases:
    hci: postgres
    hci_dev: postgres_dev
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  postgresql:
    version: '13'
  teamId: acid
  users:
    postgres: []
    postgres_dev: []
  volume:
    size: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-endpoint
  namespace: hci
  annotations:
    external-dns.alpha.kubernetes.io/hostname: db.hci.realliance.net
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: psql
  selector:
    cluster-name: acid-database
  type: LoadBalancer
