---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: hci-db
  namespace: hci
spec:
  databases:
    hci: postgres
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  postgresql:
    version: '13'
  teamId: acid
  users:
    postgres: []
  volume:
    size: 4Gi
