---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bng-mc
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      version: 3.0.3
  interval: 1m0s
  releaseName: bng-mc
  targetNamespace: christopherjmiller
  values:
    resources:
      requests:
        memory: 3Gi
        cpu: 750m
    minecraftServer:
      eula: 'TRUE'
      version: '1.17'
      type: VANILLA
      difficulty: hard
      maxPlayers: 8
      hardcore: true
      pvp: true
      icon: https://raw.githubusercontent.com/ChristopherJMiller/bng-site/master/assets/bng_discord_icon.png
      whitelist: Realmic
      ops: Realmic
      motd: BNG Hardcore MC
      jvmXXOpts: -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:G1HeapRegionSize=32M -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20
        -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication
      memory: 3072M
      serviceType: LoadBalancer
    persistence:
      dataDir:
        enabled: true
        Size: 6Gi
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: mc.brokenneckgang.com
