---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bng-mc
  namespace: flux-system
spec:
  chart:
    spec:
      chart: itzg/minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
      version: 14.5.1
  interval: 1m0s
  releaseName: bng-mc
  targetNamespace: christopherjmiller
  values:
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
    minecraftServer:
      eula: 'TRUE'
      version: 1.16.5
      type: PAPER
      difficulty: normal
      maxPlayers: 16
      levelSeed: '-707560306871759527'
      pvp: true
      motd: Broken Neck Game MC
      memory: 2048M
      extraPort:
        containerPort: 8123
        service:
          enabled: true
          port: 8123
    persistence:
      dataDir:
        enabled: true
        Size: 6Gi
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: mc.brokenneckgang.com
